### ISSUE TITLE
Become a jazzband project?

### ISSUE THREAD

**Issue by EmilStenstrom** [EmilStenstrom/django-components#284]
As @lemontheme continues to improve the code and add awesome new features, I'm thinking about the more "boring" parts. One of them is how we can lend trustworthiness to the project. Today there's "EmilStenstrom" in the URL at the top of the project, which makes things look like this is my project. But I've not been a meaningful contributor in terms of code for a while. So I would rather this be a community project, where I'm one of the contributors to.

One way to change this is to move this project from my personal github username, to an organization. This make the structure resemble how I'm hoping the project will live on, as a project where all member steer the direction, not with me as a BDFL.

Looking at what kind of org would fit, I stumbled over jazzband. It is community led, has a good set of [guidelines](https://jazzband.co/about/guidelines) that I think makes sense. And there's a big groups of people that are involved in supporting it's projects. 

Additionally, there are a lot of [django projects](https://jazzband.co/projects) that are part of jazzband, so contributors to the other projects are likely to know django enough to be a contributor here too. @jezdez, who's running the show as a "roadie", is a former (?) django core contributor.

So the open question: Should be part of jazzband?

**Comment by lemontheme** [comment]
Thanks for looking out for the boring parts!

Jazzband, which, incredibly, I've only now just heard of, certainly seems like a good fit.

> there are a lot of django projects

Holy moly, you weren't kidding! And pip-tools is in there too! <3

If your aim is to get rid of the BDFL responsibility, then I'd gladly continue contributing as a Jazzband member. I personally have no issue with your name being in the project URL – in fact, that kind of personal accountability might actually have a positive effect on how new users assess the project's trustworthiness. But it's no doubt extra responsibility, so I can see why you'd rather distribute it among multiple maintainers.

The Jazzband website doesn't explain how members are assigned to projects. It looks like this happens through the issue tracker of the [help](https://github.com/jazzband/help/issues) project?

One concern I have about moving away from your iron-fisted dictatorial rule is how do we maintain vision/focus? I'm sure there are well-studied processes to manage a greater number of cooks stirring the same pot, e.g. a central 'steering committee' sort of thing, enhancement proposals, etc.

A second concern is that, since jezdez is the _only_ roadie, making him the sole arbiter in matters that need resolving, are we effectively not swapping one BDFL for another BDFL with extra steps? Not that I mind, but it's slightly ironic.

**Comment by hanifbirgani** [comment]
I am okay with your name in the URL cause you created this fantastic project.

Rebranding aside, I don't know how moving under the Jazzband brand will affect the project's future and decision-making.

**Comment by EmilStenstrom** [comment]
Bah. I read up on the state of the jazzband project, and it seems like there's indeed only one Roadie, and that [Roadie is overwhelmed by other stuff](https://github.com/jazzband/help/issues/196), which makes the project as a whole suffer. 

Given that you are both OK with my name being in the repo name, let's keep it that way for a while longer then. Not as a sign of "who's in charge" but as a "it started here"-marker.

**Comment by lemontheme** [comment]
> Given his extensive track record, I'd have no problem trusting him.

In light of the linked thread, I retract my previous statement. 🙃

Such a shame. Our solitary roadie was definitely onto something. I hope they figures it out someday.

> Not as a sign of "who's in charge" but as a "it started here"-marker.

I'm honestly fine with either interpretation. ;) 

Do you know what I think might also work? Just create a GH org named 'django-components'. That would give the URL 'django-components/django-components'. I mean, it's not exactly pretty, but I've seen it done before and it addresses the point about your name being associated with the project. 🤷‍♀️
