### ISSUE TITLE
I cant seem to get django-components working

### ISSUE THREAD

**Issue by baseplate-admin** [EmilStenstrom/django-components#321]
Hi thanks for this awesome libaray, But i cant seem to get it working.

Here's the PR with  Changes : https://github.com/baseplate-admin/CoreProject/pull/2725/commits/43956143324fa98537285d8a237366aa2b6fb997

And here's the error i face:

![image](https://github.com/EmilStenstrom/django-components/assets/61817579/cb973ebf-7a7c-41ad-aa10-537bd6ed50f1)

What could be the reason behind this

**Comment by EmilStenstrom** [comment]
Hi! Thanks for providing enough context to properly help you find the problem.

All the setup seems to work like it should (the component tag is found for instance). Instead, the problem is that your vercel_hover component isn't found. The code for finding the components is here: https://github.com/EmilStenstrom/django-components/blob/master/django_components/__init__.py#L17

As you see, it looks for a component directory in each app you have, and otherwise falls back to your "libraries" setting which you can find docs for here: https://github.com/EmilStenstrom/django-components#configure-the-module-where-components-are-loaded-from

All in all, I think the solution is as simple as pointing to your components dir with the libraries settings.

Can you get it working?

**Comment by baseplate-admin** [comment]
Yep, Sorry for late reply.

I see the error. 

![image](https://github.com/EmilStenstrom/django-components/assets/61817579/5092cc66-d701-4734-b35d-c9bf241818b8)


This structure works

While this one doesn't

![image](https://github.com/EmilStenstrom/django-components/assets/61817579/55e76a02-27fb-4486-85a5-7703e50b669a)


Is it possible to specify the parent directory for components?

Thanks a bunch

**Comment by EmilStenstrom** [comment]
So, did you try the libraries setting i mentioned above?

**Comment by baseplate-admin** [comment]
> So, did you try the libraries setting i mentioned above?

Yep i did, Specifically [this](https://github.com/EmilStenstrom/django-components#configure-the-module-where-components-are-loaded-from).

But if i have hundreds of modules, it would be a bit tedious to load them one by one, no?

**Comment by baseplate-admin** [comment]
This issue is resolved. Thanks for your help @EmilStenstrom
