### ISSUE TITLE
Slot is not executed in conditional {% if %} block

### ISSUE THREAD

**Issue by danjac** [EmilStenstrom/django-components#37]
I have this component template:

```
<div>
...
{% if show_extra %}
{% slot extra_text %}{% endslot %}
{% endif %}
</div>
```

And in another template:
```

{% component_block "mycomponent" show_extra=True %}
{% slot extra_text %}show me!{% endslot %}
{% endcomponent_block %}

```
The text "show me!" is not rendered, just the slot default content. Overriden {% block %} content on the other hand is rendered inside a conditional.

**Comment by danjac** [comment]
I wonder if this is related to https://github.com/EmilStenstrom/django-components/issues/34: the current implementation of slots as a simple list doesn't work in when the slots themselves are executed conditionally.

**Comment by EmilStenstrom** [comment]
Interesting, you are a great tester for this project! :) I think we should do whatever block is doing, makes sense.

**Comment by jereze** [comment]
Hi,
I noticed the same behavior.

**Comment by EmilStenstrom** [comment]
@jereze Would you mind helping out fixing it? A PR that adds a test that shows the error would be a great start for instance.

**Comment by rbeard0330** [comment]
> I wonder if this is related to #34: the current implementation of slots as a simple list doesn't work when the slots themselves are executed conditionally.

I think this is right.  The current implementation looks at the components nodelist, identifies any slot nodes *in that nodelist*, then replaces them with either the provided content or the default content.  In both of these issues, the problem is that there is a slot nested within some other node (either an `IfNode` or another slot).  If that happens, then the `SlotNode` isn't removed when the template is compiled, and it renders itself using its default content.

You could potentially fix this by making the search for slots recursive.  In conjunction with that, I think you'd also want to modify the slot's own nodelist rather than replacing it like we do currently, to minimize the chance that we violate some other node's expectations.
