### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by BradleyKirton** [EmilStenstrom/django-components#9]
Hi @EmilStenstrom, thank you for the cool library.

I have a feature request which I would be happy to implement and make a PR for.

You have a template tag for loading the component js and css `component_dependencies_tag`. This would more than likely be included in the head of the document. Since the script tags generated by the Media render function are currently not deferred I would like to be able to insert the js dependencies at the bottom of the body of the document.

Django already has 2 methods on the Media class to render these assets separately [link](https://github.com/django/django/blob/779e615e362108862f1681f965ee9e4f1d0ae6d2/django/forms/widgets.py#L80).

So my proposal is to add 2 additional template tags which could be called should the user wish to split the js and css in their document.

- component_css_dependencies_tag
- component_js_dependencies_tag

Let me know your thoughts.

**Comment by EmilStenstrom** [comment]
Sounds like a great addition, makes sense to load the us in the footer.

One alternative would be to use the same tag, but with a variable: only_js=true, only_css=true. That would decrease the API area a bit, but I’m not sure I like it better.

If these tags are added, I’m wondering if we should remove the other way? Kinda makes sense since you can get the other effect by putting both tags in head if you want to.

Thoughts?

**Comment by BradleyKirton** [comment]
Hi @EmilStenstrom, my preference would be to have three tags.

If we remove the existing one there will be some backwards incompatibility for any existing users so I don't think we should do that. Let me make a PR with a proposal :)
